import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/presentation/feedback_one_page/feedback_one_page.dart';import 'package:goseedme/widgets/custom_bottom_bar.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';
// ignore_for_file: must_be_immutable
class FeedbackScreen extends StatelessWidget {FeedbackScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 25.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 282.v, width: 275.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgEllipse84, height: 215.v, width: 179.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(top: 6.v)), Align(alignment: Alignment.topRight, child: Container(width: 190.h, margin: EdgeInsets.only(top: 34.v, right: 6.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Welcome to our ", style: CustomTextStyles.headlineSmallff000000), TextSpan(text: "Feedback Page!", style: CustomTextStyles.headlineSmallff306064)]), textAlign: TextAlign.center))), CustomImageView(imagePath: ImageConstant.imgRobotBlue600, height: 168.v, width: 197.h, alignment: Alignment.bottomRight), CustomImageView(imagePath: ImageConstant.img4894890131Rig, height: 12.v, width: 26.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 23.h), onTap: () {onTapImgRig(context);})])), SizedBox(height: 37.v), Align(alignment: Alignment.centerRight, child: Container(height: 164.v, width: 272.h, margin: EdgeInsets.only(right: 22.h), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.topRight, child: Container(height: 143.v, width: 147.h, decoration: BoxDecoration(color: appTheme.blueGray50, borderRadius: BorderRadius.circular(73.h)))), Align(alignment: Alignment.topLeft, child: SizedBox(width: 239.h, child: Text("Thank you for taking the time to share your thoughts and experiences with us. Your feedback is an invaluable resource that helps us enhance the tree planting app and create a more rewarding experience for you and our global community.", maxLines: 6, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmallBluegray6000110))), CustomElevatedButton(height: 45.v, width: 134.h, text: "Start Feedback", margin: EdgeInsets.only(left: 48.h), buttonStyle: CustomButtonStyles.fillBlueGrayTL22, buttonTextStyle: CustomTextStyles.labelLargeWhiteA70013, onPressed: () {onTapStartFeedback(context);}, alignment: Alignment.bottomLeft)]))), SizedBox(height: 2.v)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Restore16: return AppRoutes.feedbackOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.feedbackOnePage: return FeedbackOnePage(); default: return DefaultWidget();} } 
/// Navigates to the homeTabContainerScreen when the action is triggered.
onTapImgRig(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeTabContainerScreen); } 
/// Navigates to the feedbackOneContainerScreen when the action is triggered.
onTapStartFeedback(BuildContext context) { Navigator.pushNamed(context, AppRoutes.feedbackOneContainerScreen); } 
 }
