import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/widgets/app_bar/appbar_subtitle.dart';import 'package:goseedme/widgets/app_bar/appbar_title_image.dart';import 'package:goseedme/widgets/app_bar/custom_app_bar.dart';import 'package:goseedme/widgets/custom_drop_down.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';import 'package:goseedme/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class PurchaseOneScreen extends StatelessWidget {PurchaseOneScreen({Key? key}) : super(key: key);

TextEditingController firstNameController = TextEditingController();

List<String> dropdownItemList = ["Item One", "Item Two", "Item Three"];

List<String> dropdownItemList1 = ["Item One", "Item Two", "Item Three"];

TextEditingController emailController = TextEditingController();

List<String> dropdownItemList2 = ["Item One", "Item Two", "Item Three"];

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 31.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 27.h), child: Text("First name", style: CustomTextStyles.labelLarge13)), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(left: 27.h, right: 32.h), child: CustomTextFormField(controller: firstNameController, hintText: "Emma ", alignment: Alignment.center, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 1.v, 6.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgCheckmarksymbol758x7581, height: 25.adaptSize, width: 25.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 37.v))), SizedBox(height: 42.v), Padding(padding: EdgeInsets.only(left: 27.h), child: Text("Last name", style: CustomTextStyles.labelLarge13)), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 27.h, right: 32.h), child: CustomDropDown(icon: Container(margin: EdgeInsets.only(left: 30.h, right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgCheckmarksymbol758x7581, height: 25.adaptSize, width: 25.adaptSize)), hintText: "Stone", hintStyle: CustomTextStyles.labelLargeMedium_1, alignment: Alignment.center, items: dropdownItemList, contentPadding: EdgeInsets.symmetric(vertical: 2.v), borderDecoration: DropDownStyleHelper.underLineGray, filled: false, onChanged: (value) {})), SizedBox(height: 43.v), Padding(padding: EdgeInsets.only(left: 27.h), child: Text("Shipping", style: CustomTextStyles.labelLarge13)), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 27.h, right: 26.h), child: CustomDropDown(hintText: "Private person", alignment: Alignment.center, items: dropdownItemList1, borderDecoration: DropDownStyleHelper.outlinePrimaryTL5, onChanged: (value) {})), SizedBox(height: 43.v), Padding(padding: EdgeInsets.only(left: 27.h), child: Text("Email", style: CustomTextStyles.labelLarge13)), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 27.h, right: 26.h), child: CustomTextFormField(controller: emailController, hintText: "emmastoneee@gmail.com", hintStyle: CustomTextStyles.labelLargeMedium, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, alignment: Alignment.center, contentPadding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 9.v))), SizedBox(height: 38.v), Padding(padding: EdgeInsets.only(left: 27.h), child: Text("Payment", style: CustomTextStyles.labelLarge13)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 27.h, right: 26.h), child: CustomDropDown(hintText: "Credit card...", alignment: Alignment.center, items: dropdownItemList2, onChanged: (value) {})), SizedBox(height: 31.v), _buildPlaceOrderColumn(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 23.h, right: 140.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.img4894890131Rig, margin: EdgeInsets.only(top: 15.v), onTap: () {onTapRig(context);}), AppbarSubtitle(text: "Ship & Pay", margin: EdgeInsets.only(left: 91.h, bottom: 4.v))])), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: SizedBox(width: double.maxFinite, child: Divider(color: appTheme.gray40093)))]), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildPlaceOrderColumn(BuildContext context) { return Container(margin: EdgeInsets.only(left: 1.h), padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 13.v), decoration: AppDecoration.outlinePrimary5.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 7.h, right: 25.h), child: _buildTaxRow(context, taxText: "1 item", priceText: "10")), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 7.h, right: 25.h), child: _buildTaxRow(context, taxText: "Tax", priceText: "1")), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 7.h, right: 25.h), child: _buildTaxRow(context, taxText: "Delivery fee", priceText: "5")), SizedBox(height: 8.v), Divider(color: appTheme.gray50004, endIndent: 12.h), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 7.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Total", style: theme.textTheme.titleLarge), Text("16", style: theme.textTheme.titleLarge)])), SizedBox(height: 24.v), CustomElevatedButton(text: "Place order", margin: EdgeInsets.only(left: 7.h, right: 12.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL101, alignment: Alignment.center), SizedBox(height: 14.v)])); } 
/// Common widget
Widget _buildTaxRow(BuildContext context, {required String taxText, required String priceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 4.v), child: Text(taxText, style: theme.textTheme.bodyMedium!.copyWith(color: theme.colorScheme.primary.withOpacity(1)))), Padding(padding: EdgeInsets.only(top: 4.v), child: Text(priceText, style: theme.textTheme.bodyMedium!.copyWith(color: theme.colorScheme.primary.withOpacity(1))))]); } 
/// Navigates to the purchaseScreen when the action is triggered.
onTapRig(BuildContext context) { Navigator.pushNamed(context, AppRoutes.purchaseScreen); } 
 }
