import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/presentation/donation_history_daily_page/donation_history_daily_page.dart';import 'package:goseedme/presentation/feedback_one_page/feedback_one_page.dart';import 'package:goseedme/widgets/custom_bottom_bar.dart';class DonationHistoryDailyTabContainerScreen extends StatefulWidget {const DonationHistoryDailyTabContainerScreen({Key? key}) : super(key: key);

@override DonationHistoryDailyTabContainerScreenState createState() =>  DonationHistoryDailyTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class DonationHistoryDailyTabContainerScreenState extends State<DonationHistoryDailyTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override void initState() { super.initState(); tabviewController = TabController(length: 8, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 23.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.img4894890131Rig, height: 12.v, width: 26.h, margin: EdgeInsets.only(top: 17.v), onTap: () {onTapImgRig(context);}), Container(height: 23.v, width: 114.h, margin: EdgeInsets.only(left: 73.h, bottom: 6.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Your Donations", style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: SizedBox(height: 23.v, width: 114.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Your Donations", style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: SizedBox(height: 23.v, width: 114.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Your Donations", style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: Text("Your Donations", style: theme.textTheme.titleSmall))])))])))]))])), SizedBox(height: 31.v), _buildDonationHistoryStack(context), SizedBox(height: 16.v), Container(height: 23.v, width: 124.h, margin: EdgeInsets.only(left: 26.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Donation History", textAlign: TextAlign.center, style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: SizedBox(height: 23.v, width: 124.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Donation History", textAlign: TextAlign.center, style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: SizedBox(height: 23.v, width: 124.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Donation History", textAlign: TextAlign.center, style: theme.textTheme.titleSmall)), Align(alignment: Alignment.center, child: Text("Donation History", textAlign: TextAlign.center, style: theme.textTheme.titleSmall))])))])))])), SizedBox(height: 9.v), _buildTabview(context), _buildTabBarView(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildDonationHistoryStack(BuildContext context) { return Align(alignment: Alignment.center, child: SizedBox(height: 136.v, width: 314.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 26.h, top: 22.v, right: 180.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 18.v, width: 87.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Total Donation", style: CustomTextStyles.labelLargeBluegray400)), Align(alignment: Alignment.center, child: SizedBox(height: 18.v, width: 87.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Total Donation", style: CustomTextStyles.labelLargeBluegray400)), Align(alignment: Alignment.center, child: Text("Total Donation", style: CustomTextStyles.labelLargeBluegray400))])))])), SizedBox(height: 2.v), SizedBox(height: 48.v, width: 108.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("4,380", textAlign: TextAlign.center, style: theme.textTheme.headlineLarge)), Align(alignment: Alignment.center, child: SizedBox(height: 48.v, width: 108.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("4,380", textAlign: TextAlign.center, style: theme.textTheme.headlineLarge)), Align(alignment: Alignment.center, child: Text("4,380", textAlign: TextAlign.center, style: theme.textTheme.headlineLarge))])))]))]))), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 22.v), decoration: AppDecoration.fillBluegray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Total Donation", style: CustomTextStyles.labelLargeBluegray400), SizedBox(height: 2.v), Text("4,380", textAlign: TextAlign.center, style: theme.textTheme.headlineLarge), SizedBox(height: 23.v)])))]))); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 24.v, width: 314.h, decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(12.h)), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, tabs: [Tab(child: Text("Daily")), Tab(child: Text("Daily")), Tab(child: Text("Daily")), Tab(child: Text("Daily")), Tab(child: Text("Monthly")), Tab(child: Text("Monthly")), Tab(child: Text("Monthly")), Tab(child: Text("Monthly"))])); } 
/// Section Widget
Widget _buildTabBarView(BuildContext context) { return SizedBox(height: 259.v, child: TabBarView(controller: tabviewController, children: [DonationHistoryDailyPage(), DonationHistoryDailyPage(), DonationHistoryDailyPage(), DonationHistoryDailyPage(), DonationHistoryDailyPage(), DonationHistoryDailyPage(), DonationHistoryDailyPage(), DonationHistoryDailyPage()])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Restore16: return AppRoutes.feedbackOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.feedbackOnePage: return FeedbackOnePage(); default: return DefaultWidget();} } 
/// Navigates to the homeTabContainerScreen when the action is triggered.
onTapImgRig(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeTabContainerScreen); } 
 }
