import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/presentation/feedback_one_page/feedback_one_page.dart';import 'package:goseedme/presentation/trees_profile_page/trees_profile_page.dart';import 'package:goseedme/widgets/custom_bottom_bar.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';class TreesProfilePageTabContainerScreen extends StatefulWidget {const TreesProfilePageTabContainerScreen({Key? key}) : super(key: key);

@override TreesProfilePageTabContainerScreenState createState() =>  TreesProfilePageTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class TreesProfilePageTabContainerScreenState extends State<TreesProfilePageTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.blueGray50, body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 331.v, width: double.maxFinite, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 18.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 12.v), CustomImageView(imagePath: ImageConstant.img4894890131Rig, height: 12.v, width: 26.h, onTap: () {onTapImgRig(context);}), SizedBox(height: 237.v), Align(alignment: Alignment.centerRight, child: Container(height: 34.v, width: 81.h, margin: EdgeInsets.only(right: 3.h), decoration: BoxDecoration(color: appTheme.blueGray400.withOpacity(0.23), borderRadius: BorderRadius.circular(17.h))))]))), CustomImageView(imagePath: ImageConstant.imgEllipse91205x151, height: 205.v, width: 151.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 11.v)), CustomImageView(imagePath: ImageConstant.imgEllipse902, height: 144.v, width: 78.h, alignment: Alignment.bottomLeft, margin: EdgeInsets.only(bottom: 52.v)), _buildRigColumn(context)])), _buildTabBarView(context)]))), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildRigColumn(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 25.h, right: 46.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.only(right: 77.h), color: appTheme.whiteA700, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder56), child: Container(height: 113.adaptSize, width: 113.adaptSize, decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder56), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 113.adaptSize, width: 113.adaptSize, decoration: BoxDecoration(color: appTheme.blueGray60001, borderRadius: BorderRadius.circular(56.h), boxShadow: [BoxShadow(color: theme.colorScheme.primary, spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))]))), CustomImageView(imagePath: ImageConstant.imgEllipse2883x83, height: 83.adaptSize, width: 83.adaptSize, radius: BorderRadius.circular(41.h), alignment: Alignment.center)]))), SizedBox(height: 21.v), Padding(padding: EdgeInsets.only(right: 83.h), child: Text("Emma Stone", style: CustomTextStyles.titleMediumGray80002)), Padding(padding: EdgeInsets.only(right: 115.h), child: Text("Rookie", style: CustomTextStyles.labelMediumBluegray900)), SizedBox(height: 4.v), CustomElevatedButton(height: 39.v, width: 99.h, text: "53.00", margin: EdgeInsets.only(right: 84.h), leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgUser12, height: 13.adaptSize, width: 13.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimaryTL19, buttonTextStyle: CustomTextStyles.labelLargeBluegray700_1), SizedBox(height: 30.v), Container(height: 24.v, width: 288.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.blueGray700, unselectedLabelColor: appTheme.blueGray400, tabs: [Tab(child: Text("Badges")), Tab(child: Text("History")), Tab(child: Text("Trees"))]))]))); } 
/// Section Widget
Widget _buildTabBarView(BuildContext context) { return SizedBox(height: 230.v, child: TabBarView(controller: tabviewController, children: [TreesProfilePage(), TreesProfilePage(), TreesProfilePage()])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Restore16: return AppRoutes.feedbackOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.feedbackOnePage: return FeedbackOnePage(); default: return DefaultWidget();} } 
/// Navigates to the historyProfilePageScreen when the action is triggered.
onTapImgRig(BuildContext context) { Navigator.pushNamed(context, AppRoutes.historyProfilePageScreen); } 
 }
