import '../home_page/widgets/plantcard_item_widget.dart';import '../home_page/widgets/slidersection_item_widget.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class HomePage extends StatefulWidget {const HomePage({Key? key}) : super(key: key);

@override HomePageState createState() =>  HomePageState();

 }

// ignore_for_file: must_be_immutable
class HomePageState extends State<HomePage> with  AutomaticKeepAliveClientMixin<HomePage> {int sliderIndex = 1;

@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 10.v), Align(alignment: Alignment.bottomRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSliderSection(context), SizedBox(height: 10.v), Container(height: 5.v, margin: EdgeInsets.only(left: 146.h), child: AnimatedSmoothIndicator(activeIndex: sliderIndex, count: 1, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(activeDotColor: Color(0X1212121D), dotHeight: 5.v))), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Recommended for you", style: CustomTextStyles.labelMediumBluegray700)), SizedBox(height: 15.v), _buildPlantCard(context), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("What should you do?", style: CustomTextStyles.labelMediumBluegray700)), SizedBox(height: 3.v), _buildGo(context), SizedBox(height: 10.v), Container(height: 63.v, width: 313.h, margin: EdgeInsets.only(left: 1.h), decoration: BoxDecoration(color: appTheme.whiteA700))])))]))))); } 
/// Section Widget
Widget _buildSliderSection(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 22.h), child: CarouselSlider.builder(options: CarouselOptions(height: 131.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {sliderIndex = index;}), itemCount: 1, itemBuilder: (context, index, realIndex) {return SlidersectionItemWidget();})); } 
/// Section Widget
Widget _buildPlantCard(BuildContext context) { return SizedBox(height: 125.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 13.h);}, itemCount: 6, itemBuilder: (context, index) {return PlantcardItemWidget();})); } 
/// Section Widget
Widget _buildBuyAccessoriesButton(BuildContext context) { return CustomElevatedButton(width: 50.h, text: "Go", buttonStyle: CustomButtonStyles.fillBlueGrayTL15, buttonTextStyle: CustomTextStyles.labelLargeAlegreyaSansWhiteA700, onPressed: () {onTapBuyAccessoriesButton(context);}, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildGo(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h, right: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.blueGray50, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder15), child: Container(height: 98.v, width: 145.h, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlinePrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomRight, child: SizedBox(height: 27.v, width: 50.h, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgUser, height: 27.v, width: 50.h, radius: BorderRadius.circular(13.h), alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 5.v), child: Text("Go", style: CustomTextStyles.labelLargeAlegreyaSansWhiteA700)))]))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 1.h, top: 6.v, right: 13.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Boost your exp", style: CustomTextStyles.titleSmallGray80003Medium_1), SizedBox(width: 53.h, child: Text("Go to Daily quest", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelMediumGray60001Medium))])))]))), Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlinePrimary1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Buy accessories", style: CustomTextStyles.titleSmallGray80003Medium_1)), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Go to shop", style: CustomTextStyles.labelMediumGray60001Medium)), SizedBox(height: 3.v), _buildBuyAccessoriesButton(context)]))])); } 
/// Navigates to the shopOneTabContainerScreen when the action is triggered.
onTapBuyAccessoriesButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.shopOneTabContainerScreen); } 
 }
