import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/widgets/app_bar/appbar_leading_image.dart';import 'package:goseedme/widgets/app_bar/custom_app_bar.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';class ForgotPasswordScreen extends StatelessWidget {const ForgotPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 25.h, top: 127.v, right: 25.h), child: Column(children: [Text("Forgot your password?", style: CustomTextStyles.labelLargeMedium_1), SizedBox(height: 21.v), Container(width: 237.h, margin: EdgeInsets.only(left: 36.h, right: 37.h), child: Text("Please enter your email and we will send you\ninstructions for reset your password", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmallPrimaryLight11_1)), SizedBox(height: 20.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 30.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgEmail11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 1.v)), Container(height: 19.v, width: 113.h, margin: EdgeInsets.only(left: 19.h), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomRight, child: Text("Sign Up", style: CustomTextStyles.bodySmallWhiteA70012)), Align(alignment: Alignment.topLeft, child: Text("Email Address", style: CustomTextStyles.bodySmallBluegray60001))]))]))), SizedBox(height: 24.v), CustomElevatedButton(height: 39.v, width: 95.h, text: "Send", margin: EdgeInsets.only(right: 30.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL10, buttonTextStyle: CustomTextStyles.titleSmallWhiteA70014, onPressed: () {onTapSend(context);}, alignment: Alignment.centerRight), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.img4894890131Rig, margin: EdgeInsets.fromLTRB(16.h, 22.v, 318.h, 22.v), onTap: () {onTapRig(context);})); } 
/// Navigates to the registerScreen when the action is triggered.
onTapRig(BuildContext context) { Navigator.pushNamed(context, AppRoutes.registerScreen); } 
/// Navigates to the resetPasswordScreen when the action is triggered.
onTapSend(BuildContext context) { Navigator.pushNamed(context, AppRoutes.resetPasswordScreen); } 
 }
