import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/widgets/custom_outlined_button.dart';class DonationHistoryDetailsOneBottomsheet extends StatelessWidget {const DonationHistoryDetailsOneBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 9.v), decoration: AppDecoration.fillBluegray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 4.v, width: 46.h, decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 8.v), _buildDonationSection(context), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 5.h), child: Text("Product Details", style: theme.textTheme.labelLarge))), SizedBox(height: 12.v), _buildProductSection(context), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 4.h), child: Text("Planting Info", style: theme.textTheme.labelLarge))), SizedBox(height: 10.v), _buildPlantingSection(context), SizedBox(height: 35.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 63.h, right: 39.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 12.v), child: Text("7,10,26 Jul 2023", style: CustomTextStyles.bodySmallBluegray400_1)), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("42", textAlign: TextAlign.center, style: theme.textTheme.titleSmall))]))), SizedBox(height: 11.v)])); } 
/// Section Widget
Widget _buildDonationSection(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.all(11.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(left: 4.h, right: 2.h), child: _buildInvoiceSection(context, invoiceNumber: "Planted", seeInvoiceText: "See Details", onTapSeeInvoiceText: () {onTapTxtSeeInvoiceText(context);})), SizedBox(height: 12.v), Divider(color: appTheme.blueGray700.withOpacity(0.2)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 2.h), child: _buildInvoiceSection(context, invoiceNumber: "INV/260/MPL/4111", seeInvoiceText: "See Invoice")), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 2.h), child: _buildInvoiceSection(context, invoiceNumber: "Donation Date", seeInvoiceText: "09 August 2023, 07:06")), SizedBox(height: 6.v)])); } 
/// Section Widget
Widget _buildProductSection(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 5.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 48.v, width: 49.h, padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 3.v), decoration: AppDecoration.fillBluegray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgImageRemovebgPreview, height: 41.v, width: 22.h, alignment: Alignment.centerLeft)), Padding(padding: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Northern Red Oak", style: theme.textTheme.labelMedium), Text("1 x 13", style: CustomTextStyles.bodySmallBluegray400_1)]))]), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Total Price", style: CustomTextStyles.bodySmallBluegray4008), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("13", style: theme.textTheme.titleSmall))]), CustomOutlinedButton(width: 92.h, text: "Donate Again", margin: EdgeInsets.only(top: 3.v, bottom: 6.v), onPressed: () {onTapDonateAgain(context);})])), SizedBox(height: 2.v)])); } 
/// Section Widget
Widget _buildPlantingSection(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.all(9.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("Tree Planters", style: CustomTextStyles.bodySmallBluegray40012)), Text("Agus - SeedFund", style: CustomTextStyles.bodySmallBluegray70012)])), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 2.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("Planting ID", style: CustomTextStyles.bodySmallBluegray40012)), Text("IZ1JFV8465NDF", style: CustomTextStyles.bodySmallBluegray70012)])), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Planted On", style: CustomTextStyles.bodySmallBluegray40012), Text("Amazon forest, Brazil", style: CustomTextStyles.bodySmallBluegray70012)])), SizedBox(height: 13.v), CustomOutlinedButton(text: "See Planting Proof", margin: EdgeInsets.symmetric(horizontal: 4.h)), SizedBox(height: 6.v)])); } 
/// Common widget
Widget _buildInvoiceSection(BuildContext context, {required String invoiceNumber, required String seeInvoiceText, Function? onTapSeeInvoiceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(invoiceNumber, style: CustomTextStyles.bodySmallBluegray40012.copyWith(color: appTheme.blueGray400))), GestureDetector(onTap: () {onTapSeeInvoiceText!.call();}, child: Text(seeInvoiceText, style: CustomTextStyles.labelLargeBluegray700.copyWith(color: appTheme.blueGray700)))]); } 
/// Navigates to the donationHistoryDetailsScreen when the action is triggered.
onTapTxtSeeInvoiceText(BuildContext context) { Navigator.pushNamed(context, AppRoutes.donationHistoryDetailsScreen); } 
/// Navigates to the donationCartScreen when the action is triggered.
onTapDonateAgain(BuildContext context) { Navigator.pushNamed(context, AppRoutes.donationCartScreen); } 
 }
