import '../history_profile_page_screen/widgets/userprofile3_item_widget.dart';import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/presentation/feedback_one_page/feedback_one_page.dart';import 'package:goseedme/widgets/custom_bottom_bar.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';import 'package:goseedme/widgets/custom_icon_button.dart';
// ignore_for_file: must_be_immutable
class HistoryProfilePageScreen extends StatelessWidget {HistoryProfilePageScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.blueGray50, body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 331.v, width: double.maxFinite, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 15.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 14.v), CustomImageView(imagePath: ImageConstant.img4894890131Rig, height: 12.v, width: 26.h), SizedBox(height: 239.v), CustomImageView(imagePath: ImageConstant.imgUserBlueGray400, height: 34.v, width: 81.h, radius: BorderRadius.circular(17.h), alignment: Alignment.center)]))), CustomImageView(imagePath: ImageConstant.imgEllipse91, height: 205.v, width: 151.h, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 11.v)), CustomImageView(imagePath: ImageConstant.imgEllipse901, height: 144.v, width: 78.h, alignment: Alignment.bottomLeft, margin: EdgeInsets.only(bottom: 52.v)), _buildRecentOrders(context)])), SizedBox(height: 9.v), _buildUserProfile(context)]))), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildRecentOrders(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 25.h, right: 45.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.only(right: 78.h), color: appTheme.whiteA700, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder56), child: Container(height: 113.adaptSize, width: 113.adaptSize, decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder56), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 113.adaptSize, width: 113.adaptSize, decoration: BoxDecoration(color: appTheme.blueGray60001, borderRadius: BorderRadius.circular(56.h), boxShadow: [BoxShadow(color: theme.colorScheme.primary, spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 4))]))), CustomImageView(imagePath: ImageConstant.imgEllipse2883x83, height: 83.adaptSize, width: 83.adaptSize, radius: BorderRadius.circular(41.h), alignment: Alignment.center)]))), SizedBox(height: 21.v), Container(height: 40.v, width: 101.h, margin: EdgeInsets.only(right: 83.h), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Text("Emma Stone", style: CustomTextStyles.titleMediumPrimary)), Align(alignment: Alignment.bottomCenter, child: Text("Rookie", style: CustomTextStyles.labelMediumBluegray900))])), SizedBox(height: 3.v), CustomElevatedButton(height: 39.v, width: 99.h, text: "53.00", margin: EdgeInsets.only(right: 85.h), leftIcon: Container(margin: EdgeInsets.only(right: 6.h), child: CustomImageView(imagePath: ImageConstant.imgUser12, height: 13.adaptSize, width: 13.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimaryTL19, buttonTextStyle: CustomTextStyles.labelLargeBluegray700_1), SizedBox(height: 30.v), Row(mainAxisAlignment: MainAxisAlignment.end, children: [Text("Badges", style: CustomTextStyles.titleSmallBluegray400), Spacer(flex: 52), Text("History", style: CustomTextStyles.titleSmallBluegray700_1), Spacer(flex: 47), GestureDetector(onTap: () {onTapTxtTrees(context);}, child: Text("Trees", style: CustomTextStyles.titleSmallBluegray400))])]))); } 
/// Section Widget
Widget _buildUserProfile(BuildContext context) { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 285.v, width: 336.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(right: 20.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Recent", textAlign: TextAlign.center, style: theme.textTheme.labelLarge)), SizedBox(height: 10.v), ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 15.v);}, itemCount: 3, itemBuilder: (context, index) {return Userprofile3ItemWidget();})]))), Padding(padding: EdgeInsets.only(left: 131.h, bottom: 40.v), child: CustomIconButton(height: 47.adaptSize, width: 47.adaptSize, padding: EdgeInsets.all(7.h), alignment: Alignment.bottomLeft, child: CustomImageView(imagePath: ImageConstant.imgGroup137))), CustomImageView(imagePath: ImageConstant.imgUntitled1179x83, height: 79.v, width: 83.h, alignment: Alignment.bottomRight)]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Restore16: return AppRoutes.feedbackOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.feedbackOnePage: return FeedbackOnePage(); default: return DefaultWidget();} } 
/// Navigates to the treesProfilePageTabContainerScreen when the action is triggered.
onTapTxtTrees(BuildContext context) { Navigator.pushNamed(context, AppRoutes.treesProfilePageTabContainerScreen); } 
 }
