import 'package:flutter/material.dart';import 'package:goseedme/core/app_export.dart';import 'package:goseedme/widgets/custom_elevated_button.dart';class DonationCartScreen extends StatelessWidget {const DonationCartScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 5.v), Expanded(child: SingleChildScrollView(child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 23.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.img4894890131Rig, height: 12.v, width: 26.h, margin: EdgeInsets.only(top: 16.v)), Padding(padding: EdgeInsets.only(left: 114.h, bottom: 5.v), child: Text("Cart", style: theme.textTheme.titleSmall))]))), SizedBox(height: 23.v), Divider(color: appTheme.gray40093), SizedBox(height: 12.v), _buildRigRow(context), SizedBox(height: 174.v), _buildGoToCheckoutColumn(context)])))])))); } 
/// Section Widget
Widget _buildRigRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 23.h, right: 28.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgImageRemovebgPreview, height: 132.v, width: 73.h, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 19.h, top: 25.v, bottom: 72.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Northern Red oak", style: CustomTextStyles.bodySmallPrimary10), SizedBox(height: 7.v), Text("13", style: CustomTextStyles.labelMedium10)])), Spacer(), Container(height: 17.adaptSize, width: 17.adaptSize, margin: EdgeInsets.only(top: 115.v, bottom: 3.v), padding: EdgeInsets.all(2.h), decoration: AppDecoration.outlinePrimary4.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgPlus, height: 8.adaptSize, width: 8.adaptSize, alignment: Alignment.centerLeft)), Padding(padding: EdgeInsets.only(left: 18.h, top: 112.v), child: Text("1", style: CustomTextStyles.bodyMedium15)), Container(height: 17.adaptSize, width: 17.adaptSize, margin: EdgeInsets.only(left: 20.h, top: 115.v, bottom: 3.v), padding: EdgeInsets.symmetric(horizontal: 2.h, vertical: 6.v), decoration: AppDecoration.outlinePrimary4.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgVector88, height: 1.v, width: 11.h, alignment: Alignment.bottomCenter))])); } 
/// Section Widget
Widget _buildGoToCheckoutColumn(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 24.v), decoration: AppDecoration.outlinePrimary5.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 7.h, right: 26.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("1 item", style: theme.textTheme.bodyMedium), SizedBox(height: 1.v), Text("Tax", style: theme.textTheme.bodyMedium)])), Padding(padding: EdgeInsets.only(top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("13", style: theme.textTheme.bodyMedium)), SizedBox(height: 1.v), Text("2", style: theme.textTheme.bodyMedium)]))])), SizedBox(height: 9.v), Divider(color: appTheme.gray50004, endIndent: 13.h), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 7.h, right: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Total", style: theme.textTheme.titleLarge), Text("15", style: theme.textTheme.titleLarge)])), SizedBox(height: 26.v), CustomElevatedButton(height: 37.v, text: "Go to Checkout", margin: EdgeInsets.only(left: 7.h, right: 13.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL101, onPressed: () {onTapGoToCheckout(context);}, alignment: Alignment.center), SizedBox(height: 40.v)])); } 
/// Navigates to the donationPurchaseScreen when the action is triggered.
onTapGoToCheckout(BuildContext context) { Navigator.pushNamed(context, AppRoutes.donationPurchaseScreen); } 
 }
